spring:
  datasource:
    testWhileIdle: true
    validationQuery: "SELECT 1"
auth:
  password: "{noop}${API_PASSWORD}"
cloud:
  aws:
    rds:
      instances:
        - db-instance-identifier: beans-sql-db
          username: ${DB_USER}
          password: ${DB_PASSWORD}
          databaseName: monolith
    region:
      static: us-west-2
      auto: false