spring:
  datasource:
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 3600000
    validationQuery: "SELECT 1"
    tomcat:
      testOnBorrow: true
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 3600000
      validationQuery: "SELECT 1"
    dbcp:
      testOnBorrow: true
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 3600000
      validationQuery: "SELECT 1"
access:
  key:
    id: ${AWS_ACCESS_KEY_ID}
    secret: ${AWS_SECRET_ACCESS_KEY}
auth:
  password: "{noop}${API_PASSWORD}"
cloud:
  aws:
    rds:
      instances:
        - db-instance-identifier: beans-sql-db
          username: ${DB_USER}
          password: ${DB_PASSWORD}
          databaseName: monolith
    region:
      static: us-west-2
      auto: false