spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  error:
    includeMessage: always
aws:
  region: us-west-2
  rds:
    jdbcUrl: "jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    maximumPoolSize: 30
access:
  key:
    id: ${AWS_ACCESS_KEY_ID}
    secret: ${AWS_SECRET_ACCESS_KEY}
logging:
  level:
    org.springframework.web: INFO
